"""fix message fields

Revision ID: 57be2a92ddd5
Revises: 6a351fb60ab9
Create Date: 2025-04-17 03:10:52.595718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57be2a92ddd5'
down_revision = '6a351fb60ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
